apiVersion: v1
kind: ConfigMap
metadata: {name: canary-page}
data:
  index.html: "<html><body><p>CANARY v2</p></body></html>"
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: app-canary}
spec:
  replicas: 1
  selector: {matchLabels: {app: myapp-canary, track: canary}}
  template:
    metadata: {labels: {app: myapp-canary, track: canary}}
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports: [{containerPort: 80}]
          volumeMounts: [{name: page, mountPath: /usr/share/nginx/html, readOnly: true}]
      volumes: [{name: page, configMap: {name: canary-page}}]
