{{- if .Values.monitoring.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helpdesk
  labels: {release: monitoring}
spec:
  selector:
    matchLabels: {app: helpdesk-backend}
  endpoints: [{port: http, path: /metrics, interval: 15s}]
{{- end }}
