apiVersion: v1
kind: ConfigMap
metadata: {name: app-blue-page}
data:
  index.html: "<html><body><p>BLUE v1</p></body></html>"
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: app-blue}
spec:
  replicas: 3
  selector: {matchLabels: {app: myapp, slot: blue}}
  template:
    metadata: {labels: {app: myapp, slot: blue}}
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports: [{containerPort: 80}]
          volumeMounts: [{name: page, mountPath: /usr/share/nginx/html, readOnly: true}]
      volumes: [{name: page, configMap: {name: app-blue-page}}]
