apiVersion: v1
kind: Service
metadata: {name: external-legacy-db}
spec:
  ports: [{name: mysql, port: 3306, targetPort: 3306, protocol: TCP}]
---
apiVersion: v1
kind: Endpoints
metadata: {name: external-legacy-db}
subsets:
  - addresses: [{ip: 192.0.2.10}]
    ports: [{name: mysql, port: 3306, protocol: TCP}]
